# vim: set noexpandtab:
# Makefile for sketch file of Spark Core.
# 
# SYNOPSIS:
#
#   make [all]  - makes everything.
#   make TARGET - makes the given target.
#   make test   - Run all tests
#   make clean  - removes all files generated by make.

SRC_DIR = .

SKETCHS = milkcarton-1.bin

all : $(SKETCHS)

milkcarton-1.bin: 
	spark compile $(SRC_DIR)/milkcarton-1.ino \
			--saveTo milkcarton-1.bin
